# Generated by Django 3.0.5 on 2020-06-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
