# Generated by Django 3.0.5 on 2020-05-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='dept',
            new_name='code',
        ),
        migrations.AddField(
            model_name='dept',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
