# Generated by Django 3.0.5 on 2020-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem',
            name='after',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sem',
            name='code',
            field=models.IntegerField(default=''),
        ),
    ]
