# Generated by Django 3.0.5 on 2020-05-23 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200521_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='code',
            new_name='code_dept',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='name',
            new_name='name_dept',
        ),
        migrations.RenameField(
            model_name='sem',
            old_name='after',
            new_name='after_sem',
        ),
        migrations.RenameField(
            model_name='sem',
            old_name='code',
            new_name='code_sem',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('DEPT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.DEPT')),
                ('SEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.SEM')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
            ],
        ),
    ]
