# Generated by Django 3.0.5 on 2020-05-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200523_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name_student',
            new_name='fullname_student',
        ),
    ]
