# Generated by Django 3.0.5 on 2020-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20200523_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fullname_student',
            new_name='full_name_student',
        ),
        migrations.AddField(
            model_name='student',
            name='name_class',
            field=models.CharField(default='', max_length=20),
        ),
    ]
