# Generated by Django 3.0.5 on 2020-05-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name_class',
        ),
    ]
