# Generated by Django 3.0.5 on 2020-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20200523_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='name_class',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='DEPT',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='SEM',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Student',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(),
        ),
    ]
