# Generated by Django 3.0.5 on 2020-05-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20200523_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Student',
            new_name='id_student',
        ),
    ]
